version: '3.4'

services:
  php:
    build:
      context: .
      target: cakephp_php
    env_file:
      - ./.docker/php.env.development
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    volumes:
      - ./app:/srv/app
      - ./.docker/php/development:/usr/local/etc/php
      - ~/.ssh/:/home/root/.ssh
    depends_on:
      - mariadb 
  mariadb:
    image: 'mariadb:10.6'
    working_dir: /application
    volumes:
      - '/Users/tsgmac/Documents/docker:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=p@55word
      - MYSQL_DATABASE=cake4
      - MYSQL_USER=cake4
      - MYSQL_PASSWORD=p@55word
    ports:
      - '8083:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cakephpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    restart: always
    ports:
      - 8081:80
    volumes:
      - data:/var/lib/cakephpmyadmin
    depends_on:
      - mariadb
  web:
    image: nginx:1.19-alpine
    working_dir: /srv/app/
    environment:
      TERM: Linux
    volumes:
      - ./app:/srv/app
      - ./.docker/nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - php
volumes:
  data:
